// Generated by gencpp from file moveit_task_constructor_gpd/PointCloud.msg
// DO NOT EDIT!


#ifndef MOVEIT_TASK_CONSTRUCTOR_GPD_MESSAGE_POINTCLOUD_H
#define MOVEIT_TASK_CONSTRUCTOR_GPD_MESSAGE_POINTCLOUD_H

#include <ros/service_traits.h>


#include <moveit_task_constructor_gpd/PointCloudRequest.h>
#include <moveit_task_constructor_gpd/PointCloudResponse.h>


namespace moveit_task_constructor_gpd
{

struct PointCloud
{

typedef PointCloudRequest Request;
typedef PointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PointCloud
} // namespace moveit_task_constructor_gpd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_task_constructor_gpd::PointCloud > {
  static const char* value()
  {
    return "94645eea953657df61f8fb2e51049aaa";
  }

  static const char* value(const ::moveit_task_constructor_gpd::PointCloud&) { return value(); }
};

template<>
struct DataType< ::moveit_task_constructor_gpd::PointCloud > {
  static const char* value()
  {
    return "moveit_task_constructor_gpd/PointCloud";
  }

  static const char* value(const ::moveit_task_constructor_gpd::PointCloud&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_task_constructor_gpd::PointCloudRequest> should match
// service_traits::MD5Sum< ::moveit_task_constructor_gpd::PointCloud >
template<>
struct MD5Sum< ::moveit_task_constructor_gpd::PointCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_task_constructor_gpd::PointCloud >::value();
  }
  static const char* value(const ::moveit_task_constructor_gpd::PointCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_task_constructor_gpd::PointCloudRequest> should match
// service_traits::DataType< ::moveit_task_constructor_gpd::PointCloud >
template<>
struct DataType< ::moveit_task_constructor_gpd::PointCloudRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_task_constructor_gpd::PointCloud >::value();
  }
  static const char* value(const ::moveit_task_constructor_gpd::PointCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_task_constructor_gpd::PointCloudResponse> should match
// service_traits::MD5Sum< ::moveit_task_constructor_gpd::PointCloud >
template<>
struct MD5Sum< ::moveit_task_constructor_gpd::PointCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_task_constructor_gpd::PointCloud >::value();
  }
  static const char* value(const ::moveit_task_constructor_gpd::PointCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_task_constructor_gpd::PointCloudResponse> should match
// service_traits::DataType< ::moveit_task_constructor_gpd::PointCloud >
template<>
struct DataType< ::moveit_task_constructor_gpd::PointCloudResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_task_constructor_gpd::PointCloud >::value();
  }
  static const char* value(const ::moveit_task_constructor_gpd::PointCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_TASK_CONSTRUCTOR_GPD_MESSAGE_POINTCLOUD_H
