// Generated by gencpp from file moveit_task_constructor_gpd/PointCloudResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_TASK_CONSTRUCTOR_GPD_MESSAGE_POINTCLOUDRESPONSE_H
#define MOVEIT_TASK_CONSTRUCTOR_GPD_MESSAGE_POINTCLOUDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_task_constructor_gpd
{
template <class ContainerAllocator>
struct PointCloudResponse_
{
  typedef PointCloudResponse_<ContainerAllocator> Type;

  PointCloudResponse_()
    {
    }
  PointCloudResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloudResponse_

typedef ::moveit_task_constructor_gpd::PointCloudResponse_<std::allocator<void> > PointCloudResponse;

typedef boost::shared_ptr< ::moveit_task_constructor_gpd::PointCloudResponse > PointCloudResponsePtr;
typedef boost::shared_ptr< ::moveit_task_constructor_gpd::PointCloudResponse const> PointCloudResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace moveit_task_constructor_gpd

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_task_constructor_gpd/PointCloudResponse";
  }

  static const char* value(const ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloudResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::moveit_task_constructor_gpd::PointCloudResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_TASK_CONSTRUCTOR_GPD_MESSAGE_POINTCLOUDRESPONSE_H
