// Generated by gencpp from file moveit_task_constructor_gpd/PointCloudRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_TASK_CONSTRUCTOR_GPD_MESSAGE_POINTCLOUDREQUEST_H
#define MOVEIT_TASK_CONSTRUCTOR_GPD_MESSAGE_POINTCLOUDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_task_constructor_gpd
{
template <class ContainerAllocator>
struct PointCloudRequest_
{
  typedef PointCloudRequest_<ContainerAllocator> Type;

  PointCloudRequest_()
    : cloud_file()  {
    }
  PointCloudRequest_(const ContainerAllocator& _alloc)
    : cloud_file(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cloud_file_type;
  _cloud_file_type cloud_file;





  typedef boost::shared_ptr< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloudRequest_

typedef ::moveit_task_constructor_gpd::PointCloudRequest_<std::allocator<void> > PointCloudRequest;

typedef boost::shared_ptr< ::moveit_task_constructor_gpd::PointCloudRequest > PointCloudRequestPtr;
typedef boost::shared_ptr< ::moveit_task_constructor_gpd::PointCloudRequest const> PointCloudRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator1> & lhs, const ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cloud_file == rhs.cloud_file;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator1> & lhs, const ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_task_constructor_gpd

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94645eea953657df61f8fb2e51049aaa";
  }

  static const char* value(const ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94645eea953657dfULL;
  static const uint64_t static_value2 = 0x61f8fb2e51049aaaULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_task_constructor_gpd/PointCloudRequest";
  }

  static const char* value(const ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request saving depth and rgb images\n"
"# Input is file names to save them as\n"
"string cloud_file\n"
;
  }

  static const char* value(const ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cloud_file);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloudRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_task_constructor_gpd::PointCloudRequest_<ContainerAllocator>& v)
  {
    s << indent << "cloud_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cloud_file);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_TASK_CONSTRUCTOR_GPD_MESSAGE_POINTCLOUDREQUEST_H
