// Generated by gencpp from file ur5_simulation/GetPosition.msg
// DO NOT EDIT!


#ifndef UR5_SIMULATION_MESSAGE_GETPOSITION_H
#define UR5_SIMULATION_MESSAGE_GETPOSITION_H

#include <ros/service_traits.h>


#include <ur5_simulation/GetPositionRequest.h>
#include <ur5_simulation/GetPositionResponse.h>


namespace ur5_simulation
{

struct GetPosition
{

typedef GetPositionRequest Request;
typedef GetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosition
} // namespace ur5_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur5_simulation::GetPosition > {
  static const char* value()
  {
    return "4931ed2ee82bda66c8bc53fd24c21c60";
  }

  static const char* value(const ::ur5_simulation::GetPosition&) { return value(); }
};

template<>
struct DataType< ::ur5_simulation::GetPosition > {
  static const char* value()
  {
    return "ur5_simulation/GetPosition";
  }

  static const char* value(const ::ur5_simulation::GetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::ur5_simulation::GetPositionRequest> should match
// service_traits::MD5Sum< ::ur5_simulation::GetPosition >
template<>
struct MD5Sum< ::ur5_simulation::GetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur5_simulation::GetPosition >::value();
  }
  static const char* value(const ::ur5_simulation::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur5_simulation::GetPositionRequest> should match
// service_traits::DataType< ::ur5_simulation::GetPosition >
template<>
struct DataType< ::ur5_simulation::GetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::ur5_simulation::GetPosition >::value();
  }
  static const char* value(const ::ur5_simulation::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur5_simulation::GetPositionResponse> should match
// service_traits::MD5Sum< ::ur5_simulation::GetPosition >
template<>
struct MD5Sum< ::ur5_simulation::GetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur5_simulation::GetPosition >::value();
  }
  static const char* value(const ::ur5_simulation::GetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur5_simulation::GetPositionResponse> should match
// service_traits::DataType< ::ur5_simulation::GetPosition >
template<>
struct DataType< ::ur5_simulation::GetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::ur5_simulation::GetPosition >::value();
  }
  static const char* value(const ::ur5_simulation::GetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR5_SIMULATION_MESSAGE_GETPOSITION_H
