// Generated by gencpp from file ur5_simulation/GetPositionRequest.msg
// DO NOT EDIT!


#ifndef UR5_SIMULATION_MESSAGE_GETPOSITIONREQUEST_H
#define UR5_SIMULATION_MESSAGE_GETPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_simulation
{
template <class ContainerAllocator>
struct GetPositionRequest_
{
  typedef GetPositionRequest_<ContainerAllocator> Type;

  GetPositionRequest_()
    : get_position(false)  {
    }
  GetPositionRequest_(const ContainerAllocator& _alloc)
    : get_position(false)  {
  (void)_alloc;
    }



   typedef uint8_t _get_position_type;
  _get_position_type get_position;





  typedef boost::shared_ptr< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPositionRequest_

typedef ::ur5_simulation::GetPositionRequest_<std::allocator<void> > GetPositionRequest;

typedef boost::shared_ptr< ::ur5_simulation::GetPositionRequest > GetPositionRequestPtr;
typedef boost::shared_ptr< ::ur5_simulation::GetPositionRequest const> GetPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_simulation::GetPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_simulation::GetPositionRequest_<ContainerAllocator1> & lhs, const ::ur5_simulation::GetPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.get_position == rhs.get_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_simulation::GetPositionRequest_<ContainerAllocator1> & lhs, const ::ur5_simulation::GetPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a61a6675ded7cb2c8471dcd8afdc3b74";
  }

  static const char* value(const ::ur5_simulation::GetPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa61a6675ded7cb2cULL;
  static const uint64_t static_value2 = 0x8471dcd8afdc3b74ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_simulation/GetPositionRequest";
  }

  static const char* value(const ::ur5_simulation::GetPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool get_position\n"
;
  }

  static const char* value(const ::ur5_simulation::GetPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_simulation::GetPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_simulation::GetPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "get_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_SIMULATION_MESSAGE_GETPOSITIONREQUEST_H
