# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /robot/limb/right
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_j0
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6
  #- name: gripper_controller
    #action_ns: follow_joint_trajectory
    #default: True
    #type: FollowJointTrajectory
    #joints:
    #  - robotiq_85_left_knuckle_joint
/robot/limb/right:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_j0
    - right_j1
    - right_j2
    - right_j3
    - right_j4
    - right_j5
    - right_j6
  gains:
    right_j0:
      p: 500
      d: 25
      i: 10
      i_clamp: 100
    right_j1:
      p: 400
      d: 30
      i: 10
      i_clamp: 400
    right_j2:
      p: 250
      d: 30
      i: 10
      i_clamp: 100
    right_j3:
      p: 300
      d: 50
      i: 10
      i_clamp: 100
    right_j4:
      p: 300
      d: 8
      i: 10
      i_clamp: 100
    righ_j5:
      p: 100
      d: 5.0
      i: 1.0
      i_clamp: 100
    righ_j6:
      p: 50
      d: 4.0
      i: 10
      i_clamp: 100
#gripper_controller:
 # type: effort_controllers/JointTrajectoryController
  #joints:
   # - robotiq_85_left_knuckle_joint
  #gains:
   # robotiq_85_left_knuckle_joint:
    #  p: 40
     # d: 0
      #i: 0
      #i_clamp: 1